### ISSUE TITLE
安装运行的时候那个提示的地址不对

### ISSUE THREAD

**Issue by chentvtchen** [monw3c/xmui#15]
![image](https://user-images.githubusercontent.com/17005933/45208764-fb54c580-b2bd-11e8-82ed-88768edde3c3.png)
![image](https://user-images.githubusercontent.com/17005933/45208771-00197980-b2be-11e8-9afd-d34416fb2221.png)
前面换成http://localhost就可以运行了

**Comment by monw3c** [comment]
或者用ip也可以
